// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Data;

namespace Recipes.Data.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20190213153958_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Recipes.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<double>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 2, 13, 15, 39, 58, 112, DateTimeKind.Local).AddTicks(9051),
                            Modified = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(2690),
                            Name = "Chilli Con Carne",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(4573),
                            Modified = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(4590),
                            Name = "Spagetti Bolognese",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(4611),
                            Modified = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(4635),
                            Name = "Chicken Tikka Masala",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(4639),
                            Modified = new DateTime(2019, 2, 13, 15, 39, 58, 121, DateTimeKind.Local).AddTicks(4644),
                            Name = "Sausage Casserole",
                            Rating = 4.2000000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
